spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MariaDBDialect
        query:
          in_clause_parameter_padding: true
  aop:
    proxy-target-class: true
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mariadb://localhost:3306/jpatest?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
    driverClassName: org.mariadb.jdbc.Driver
    validation-query: SELECT 1
    test-on-borrow: true
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  thymeleaf:
    prefix: /resources/templates/
    suffix: .html
    cache: false


